import os
import sys
import urllib.request
import csv
import tempfile
import datetime
import networkx as nx
from rdkit import Chem
from shutil import rmtree
import pickle
from rdkit.Chem import Descriptors

sys.path.append(os.path.join("..", "..", "..", "metaboblend", "metaboblend"))
from build_structures import annotate_msn


def run_test(out_dir, ms_data, max_valence, ppm, db_path, max_atoms_available=2, test_type="ind_exp"):
    """
    Wrapper for running tests for the MS2 structure generation & ranking method.

    :param out_dir: The directory in which to output results of the testing.

    :param ms_data: Dictionary generated by parse_testing_data or similar.

    :param test_name: Name of the test.

    :param heavy_atoms: Allowable heavy atoms of substructures.

    :param max_valence: Maximal valence of sets of substructures.

    :param accuracy: Accuracy of the build method.

    :param ppm: Allowable error of the build method.

    :param db_path: Path of the substructure database.

    :param test_type: The type of test to be run.

    :param subset: Whether or not to only include substructures generated by the compound of interest.

    :param max_atoms_available: Maximum atoms available for substructures used for building.
    """

    with open(os.path.join(out_dir, "results.csv"), newline="", mode="w") as overall_results:
        results_csv = csv.writer(overall_results)

        if test_type == "ind_exp":
            results_csv.writerow([
                "category",
                "HMDB_ID",
                "SMILES",
                "Precursor_Mass",
                "Num_Peaks",
                "True_Recurrence",
                "Structure_Ranking",
                "Maximal_Recurrence",
                "Total_Structures",
                "Fragment_Masses",
                "Heavy_Atoms",
                "Max_Valence",
                "Accuracy",
                "ppm"
            ])

    if test_type == "ind_exp":
        C(out_dir, ms_data, max_valence, ppm, db_path, max_atoms_available)
    else:
        raise NotImplementedError


def C(out_dir, ms_data, max_valence, ppm, db_path, max_atoms_available):
    """Run a test on MS2 data. See run_test."""

    for category in ms_data.keys():
        os.mkdir(os.path.join(out_dir, category))

        try:
            del ms_data[category][""]
        except KeyError:
            pass

        annot_msn_data = {}
        for hmdb in ms_data[category].keys():
            ms_data[category][hmdb]["neutral_precursor_ion_mass"] \
                = ms_data[category][hmdb]["precursor_ion_mass"] - 1.007276
            ms_data[category][hmdb]["neutral_peaks"] = [peak - 1.007276 for peak in ms_data[category][hmdb]["peaks"]]

            annot_msn_data[hmdb] = {}
            annot_msn_data[hmdb]["mf"] = ms_data[category][hmdb]["mc"]
            annot_msn_data[hmdb]["exact_mass"] = ms_data[category][hmdb]["neutral_precursor_ion_mass"]
            annot_msn_data[hmdb]["fragment_masses"] = ms_data[category][hmdb]["neutral_peaks"]

        for subs_freqs in annotate_msn(
                path_smi_out=os.path.join(out_dir, category),
                msn_data=annot_msn_data,
                path_substructure_db=db_path,
                path_connectivity_db="../../Data/databases/k_graphs.sqlite",
                ha_min=None, ha_max=None, max_degree=max_valence,
                ppm=ppm,
                max_atoms_available=max_atoms_available
            ):

            hmdb = list(subs_freqs.keys())[0]

            try:
                subs_freqs[hmdb][ms_data[category][hmdb]["smiles"]]
            except KeyError:
                subs_freqs[hmdb][ms_data[category][hmdb]["smiles"]] = 0

            test_build_start = datetime.datetime.now()
            with open(os.path.join(out_dir, "results.csv"), newline="", mode="a") as overall_results:
                rcsv = csv.writer(overall_results)

                rcsv.writerow([category,
                               hmdb,
                               ms_data[category][hmdb]["smiles"],
                               ms_data[category][hmdb]["neutral_precursor_ion_mass"],
                               len(ms_data[category][hmdb]["neutral_peaks"]),
                               subs_freqs[hmdb][ms_data[category][hmdb]["smiles"]],  # true recurr
                               len([freq for freq in list(subs_freqs[hmdb].values()) if freq >= subs_freqs[hmdb][ms_data[category][hmdb]["smiles"]]]),  # struct rank
                               max(subs_freqs[hmdb].values()),  # max recurr
                               len(subs_freqs[hmdb].keys()),  # tot structs
                               ms_data[category][hmdb]["neutral_peaks"],
                               max_valence,
                               ppm])

            print("test_build_time = " + str(datetime.datetime.now() - test_build_start))
